okay

diff --git a/Aurora b/Aurora
--- a/Aurora
+++ b/Aurora
@@ -100,7 +100,7 @@ echo_c "Done.\n\n${BLUE_B}Installing Rootfs Packages" GEEN_B
 chroot "$rootfs" /bin/sh -c "export PATH=/sbin:/bin:/usr/sbin:/usr/bin && chmod +x /opt/setup_rootfs_alpine.sh && /opt/setup_rootfs_alpine.sh $arch"
 echo_c "Done.\n\n${BLUE_B}Downloading firmware..." GEEN_B
 git clone --depth=1 https://chromium.googlesource.com/chromiumos/third_party/linux-firmware $rootfs/lib/firmware/
-find "$rootfs/lib/firmware" -type f -not \( -name "*wifi*" -o -name "rt*" -o -name "*com*" \) -exec rm -rf {} + >/dev/null 2>&1
+find "$rootfs/lib/firmware" -type f -not \( -path "*wifi*" -o -path "*rt*" -o -path "*ath*" -o -path "*mediatek*" \) -exec rm -rf {} + >/dev/null 2>&1
 
 trap - EXIT
 echo_c "Done.\n\n${BLUE_B}Building shim..." GEEN_B
@@ -178,7 +178,7 @@ if [ "$DEBUG" -eq "1" ]; then
     rsync -avH --info=progress2 --delete "$rootfs/." "$root_bmount"
     sleep 10
 else
-    rsync -avH --info=progress2 --delete "$rootfs/." "$root_bmount" >/dev/null 2>&1
+    rsync -avH --info=progress2 --delete "$rootfs/." "$root_bmount" >/dev/null 2>&1 || echo "failed to copy all files"; exit 1
 fi
 echo_c "Done.\n\n${BLUE_B}Copying initramfs to shim" "GEEN_B"
 rm -f "$initramfs/bin/init"
