oh

diff --git a/Aurora b/Aurora
--- a/Aurora
+++ b/Aurora
@@ -50,6 +50,41 @@ lsbval() {
   }" "$lsbfile"
 }
 
+if [ "$EUID" -ne 0 ]; then
+    echo "Please run as root."
+    exit 1
+fi
+if [ -z "$1" ]; then
+    echo "Usage: sudo bash Aurora /path/to/rawshim.bin [cpu_architecture(x86_64 or aarch64)] /path/to/payload/dir/"
+    exit 1
+fi
+if [ -z "$2" ]; then
+    read -p "CPU Architecture Unspecified. Default to x86_64? (Y/n): " cpuarch
+    case "$cpuarch" in
+        n|N)
+            read -p "Enter CPU Architecture (x86_64/aarch64): " arch
+            export arch
+            ;;
+        *)
+            arch="x86_64"
+            export arch
+            ;;
+    esac
+else
+    arch="$2"
+    export arch
+fi
+
+checkarch() {
+    if [[ "$arch" != "aarch64" && "$arch" != "x86_64" ]]; then
+        echo -e "Invalid CPU Architecture"
+        read -p "Enter CPU Architecture (x86_64/aarch64): " arch
+        export arch
+        checkarch
+    fi
+}
+checkarch
+
 shim="$1"
 arch="$2"
 [ -n "$3" ] && payloads=$(realpath -m "$3")
