a

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -40,8 +40,8 @@ shimbootselected() {
     if [ -n "$shim" ] && [ -e "$shim" ]; then
         echo -n "Enter size to allocate to shimboot rootfs [G]: "
 	read size
-	size=$(echo $size | sed 's/G//I')
-	truncate "$shim" -s +${size}G || echo "Invalid size. Please use an integer." && return 1
+	size1=$(echo $size | sed 's/G//I')
+	truncate $shim -s +"$size1"G || echo "Invalid size. Please use an integer." && return 1
 	losetup -Pf $shim
         exec /bootstrap.sh < "$TTY1" >> "$TTY1" 2>&1
     else
