what

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -1,1 +1,79 @@
 #!/bin/busybox sh
+
+auroraselected() {
+    echo "Moving mounts to /newroot"
+    mkdir -p "/newroot/sys"
+    mount -n -o move "/sys" "/newroot/sys"
+    mkdir -p "/newroot/proc"
+    mount -n -o move "/proc" "/newroot/proc"
+    mkdir -p "/newroot/dev"
+    mount -n -o move "/dev" "/newroot/dev"
+    mkdir -p /newroot/initramfs
+    pivot_root /newroot /newroot/initramfs
+    umount -l /initramfs
+    exec /sbin/init < "$TTY1" >> "$TTY1" 2>&1
+}
+
+shimbootselected() {
+    shimdir="/newroot/usr/share/aurora/images/shims/"
+    i=1
+
+    for shim in "$shimdir"/*.bin; do
+        [ -e "$shim" ] || continue
+        echo "$i) $(basename "$shim")"
+        eval "file_$i=\"\$f\""
+        i=$((i + 1))
+    done
+
+    if [ "$i" -eq 1 ]; then
+        echo "No shims found."
+        rm -f /newroot/etc/shimboot
+        return 1
+    fi
+
+    echo -n "Choose your shimboot shim: "
+    read choice
+
+    eval "shim=\$file_$choice"
+
+    if [ -n "$shim" ] && [ -e "$shim" ]; then
+        losetup -Pf $shim
+        chmod +x /bootstrap.sh && exec /bootstrap.sh < "$TTY1" >> "$TTY1" 2>&1
+    else
+        echo "Invalid choice... somehow"
+        return 1
+    fi
+}
+
+clear
+echo "Making the newroot partition..."
+mkdir -p /newroot || sleep 10
+dev_partition=$(blkid | grep 'LABEL="Aurora"' | awk -F: '{print $1}' || true)
+dev=$(echo "$dev_partition" | sed -E 's/p?[0-9]+$//')
+if [ -z "$dev_partition" ]; then
+    echo "failed to find aurora partition"
+    sleep 5
+    exit 1
+fi
+if [ -f "/.UNRESIZED" ]; then
+    chmod +x /.UNRESIZED
+    bash /.UNRESIZED
+    rm -f /.UNRESIZED
+    sync
+fi
+echo "Mounting device..."
+mount $dev_partition /newroot
+if [ -e /newroot/etc/shimboot ] || find /newroot/usr/share/aurora/images/shims/ -iname "*shimboot*" | grep -q .; then
+    while true; do
+        echo "1. Aurora [$dev_partition]"
+        echo "2. Shimboot (ONLY select this if you have a shimboot shim in Aurora's shim directory)"
+        echo "3. Shell"
+        echo -n "Enter Selection: "
+        read initselection
+        case $initselection in
+            1) auroraselected ;;
+            2) shimbootselected ;;
+            3) clear && script -qfc 'stty sane && stty erase '^H' && exec busybox sh -l' /dev/null ;;
+
+        esac
+    done
