:3

diff --git a/rootfs/usr/bin/kvs b/rootfs/usr/bin/kvs
--- a/rootfs/usr/bin/kvs
+++ b/rootfs/usr/bin/kvs
@@ -1,9 +1,11 @@
 #!/bin/bash
 
+source /usr/share/aurora/centering
+
 kvs() {
     while true; do
         clear
-        read -p "Enter Kernver[Max 8 characters after 0x]: 0x" kernver
+        read_center -d "Enter Kernver[Max 8 characters after 0x]: 0x" kernver
         mount --bind /mount /mount
         for mnt in /dev /proc /sys; do
             mkdir -p /mount$mnt
@@ -19,10 +21,10 @@ kvs() {
             echo "$vercheck"
             break
         fi
-        echo "Struct ver: $ver"
+        echo "Struct ver: $ver" | center
         break=1
-        chroot /mount sh -c 'tpmc write 0x1008 $(kvg 0x'"$kernver"' --ver='"$ver"')' || {
-            echo "Invalid Kernver. Maximum 8 characters after 0x [eg: 0x00000001]"
+        chroot /mount sh -c 'tpmc write 0x1008 $(kvg 0x'"$kernver"' --ver='"$ver"')' >/dev/null || {
+            echo "Invalid Kernver. Maximum 8 characters after 0x [e.g: 0x00000001]" | center
             break=0
         }
         for mnt in /dev /proc /sys; do
@@ -36,6 +38,6 @@ kvs() {
 if [ "$(crossystem mainfw_type)" = "recovery" ]; then
     kvs
 else
-    echo "Please boot Aurora in recovery [Esc+Ref+Pwr] to use KVS."
-    read -p "Press Enter to return to the main menu"
+    echo "Please boot Aurora in recovery [Esc+Ref+Pwr] to use KVS." | center
+    read_center "Press Enter to return to the main menu"
 fi
